repos:

  # ----------------------------------------------------------------------------
  # Remote

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        args: [--prose-wrap, always]
        types_or: [markdown]

  # ----------------------------------------------------------------------------
  # Local

  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: poetry run black
        require_serial: true
        types: [python]

      - id: isort
        name: isort
        language: system
        entry: poetry run isort
        require_serial: true
        types: [python]

      - id: flake8
        name: flake8
        language: system
        entry: poetry run flake8 --config .flake8 --statistics
        require_serial: false
        types: [python]

      - id: mypy
        name: mypy
        language: system
        entry: >-
          poetry run dmypy run
          --timeout 3600
          -- src/testbench_tuna
        require_serial: false
        pass_filenames: false
        types: [python]

  # ----------------------------------------------------------------------------

exclude: |
  (?x)^(
    CHANGELOG.md|
    poetry.lock
  )$
